# Weights for the Intelligent Candidate Ranking Challenge

SEMANTIC_WEIGHT = 0.35
SKILL_WEIGHT = 0.20
EXPERIENCE_WEIGHT = 0.15
CAREER_WEIGHT = 0.10
EDUCATION_WEIGHT = 0.05
CERTIFICATION_WEIGHT = 0.05
REDROB_SIGNALS_WEIGHT = 0.10
